### ISSUE TITLE
please add dart files to your plugin

### ISSUE THREAD

**Issue by escamoteur** [j0meinaster/bracket-peek#1]
Hi,

I was looking for a plugin like yours but it seems it is not activated in a `.dart` file.
Any chance to change that?

Cheers
Thomas

**Comment by j0meinaster** [comment]
Hi,

I have added the support for dart files, but I only tested it with a small example file found on github.

I am looking forward to your feedback :D

**Comment by j0meinaster** [comment]
solved in version 1.0.4

**Comment by escamoteur** [comment]
Awesome thanks. I had realized that suddenly it worked but didn't remember which plugin it was.

**Comment by j0meinaster** [comment]
No problem. If you are happy with it .. I would be happy with a positive review, since some negativity was spread there :D
