### ISSUE TITLE
No settings?

### ISSUE THREAD

**Issue by geekrelief** [j0meinaster/bracket-peek#17]
When I try to adjust the settings on version 1.4.2 nothing appears for "@ext:jomeinaster.bracket-peek".

**Comment by j0meinaster** [comment]
When you open the vscode preference page and type 'bracket-peek' you can see the available settings.

**Comment by geekrelief** [comment]
It's been a while since I posted this issue that I don't recall why I need to access the settings.  In anycase, I see the settings now.  Thanks!
