### ISSUE TITLE
Cannot access 'activeEditor' before initialization

### ISSUE THREAD

**Issue by Akkuma** [j0meinaster/bracket-peek#22]
VSCode 

Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:13:50.741Z (1 mo ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0

It looks like bracket-peek stopped working with the latest or more recent versions of VSCode for me as that error is preventing anything from showing.

Thanks for this extension!

**Comment by j0meinaster** [comment]
Sorry. I messed up 1.4.3.. Thanks for the report. should be fixed in 1.4.4
