### ISSUE TITLE
Preview multiple lines?

### ISSUE THREAD

**Issue by m93a** [j0meinaster/bracket-peek#4]
Some code styles put the opening brace on an empty line. This way it's impossible to see the relevant code with your extension.

It would be awesome if one could configure how many lines of preview would show up.

**Comment by j0meinaster** [comment]
Hi, thanks for the feedback.

Is it enough if the previous line of code is previewed, if a open curly bracket on a new line is detected?

**Comment by j0meinaster** [comment]
Published in 1.1.2 

Please check, if it suits your needs.

**Comment by m93a** [comment]
Thank you for your reply. It's definitely much better, but it's not enough. For example it's still quite useless in this scenario:

![image](https://user-images.githubusercontent.com/1671665/75287032-f2411680-5819-11ea-99ce-35787369bc07.png)

The preview: 
![image](https://user-images.githubusercontent.com/1671665/75287136-21f01e80-581a-11ea-9b2c-4f529207454d.png)

Furthermore I noticed that the extension adds a horizontal scrollbar every time it displays a preview, I'll start a separate issue for that.

**Comment by j0meinaster** [comment]
This is the first time I see this code style / fomat.

I will check if it is possible to implement a multi line preview.
