### ISSUE TITLE
Decorations have side effects

### ISSUE THREAD

**Issue by chrisant996** [j0meinaster/bracket-peek#9]
Decorations have side effects:
- Forces horizontal scrollbar.
- Doesn't play well with other decorations.
- Can jitter in various situations.

**Comment by chrisant996** [comment]
Using `registerHoverProvider` might be a good alternative for mouse hovering.
That doesn't look like it can show feedback from cursor navigation, though.

**Comment by chrisant996** [comment]
Oh, I get it -- it already does.

**Comment by j0meinaster** [comment]
Hi,

I got a lot of things to work in version 1.2.0 Maybe you want to check them out?

The jitter and side effects of inline decorations are solved.

See changelogs here: https://github.com/j0meinaster/bracket-peek/blob/master/CHANGELOG.md
